# Generated by Django 4.2.7 on 2024-04-15 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_remove_topic_created_remove_topic_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="movie",
            name="particpants",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
