# Generated by Django 3.2.7 on 2024-04-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_movie_options_movie_particpants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acting', models.IntegerField(default=0)),
                ('plot', models.IntegerField(default=0)),
                ('cinematography', models.IntegerField(default=0)),
                ('theme', models.IntegerField(default=0)),
                ('dialogue', models.IntegerField(default=0)),
                ('characters', models.IntegerField(default=0)),
                ('overall', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
